# GitHub Pages Configuration Variables

# The theme of your site
remote_theme: nikahmadz/pages

# The title of your site
title: Upah

# A short description of your site's purpose
description: - tiada komen -
