# GitHub Pages Configuration Variables

# The theme of your site
remote_theme: nikahmadz/pages

title: Upah # The title of your site
description: - tiada komen - # A short description of your site's purpose
header: bar
